server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-cn-uqm36mm7r0002jmo.rwlb.rds.aliyuncs.com:3306/redpacket?useSSL=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Leilei@1
  redis:
    host: r-bp1ro436w8i56cjjmjpd.redis.rds.aliyuncs.com
    password: asule:leilei@1
    port: 6379

  application:
    name: red-envelope-system

  # Springboot2.6及以上版本整合Swagger3需要此配置,否则启动会报异常:
  # Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #rabbitmq
  rabbitmq:
    #服务器
    host: 47.97.113.26
    #用户名
    username: guest
    #密码
    password: guest
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息，处理完在继续下一条消息
        prefetch: 1
        #启动是默认启动容器
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #重试最大次数，默认3次
        max-attempts: 3
        #最大重试间隔时间
        max-interval: 10000ms
        #重试的间隔乘数，比如配2。0  第一等10s 第二次等20s 第三次等40s
        multiplier: 1

#是否开启swagger3文档
springfox:
  documentation:
    enabled: true


mybatis-plus:
  type-aliases-package: com.asule.redenvelopesystem
  mapper-locations: classpath:mapper/*.xml


